test:
  workers:
    number: 5   
  rounds:
    - label: signIn
      description: signIn Benchmark
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
      workload:
        module: workload/signIn.js

     
    
